import { randomSeed } from '../randoms/seeds';
import { shuffle } from '../randoms/shuffle';
import { Scene } from './types';

const scenes: Scene[] = [
  { text: 'どうも粗品です' },
  { text: 'というわけでね' },
  { text: 'あの～' },
  { text: '今日はですね' },
  { text: '最近あった' },
  { text: 'むかついた事を' },
  { text: '喋りたいなと' },
  { text: '思うんですけども' },
  { text: 'うどん屋に行ったんです' },
  { text: 'ほなそのうどん屋で' },
  { text: 'なんか' },
  { text: '大将が出てきてね' },
  { text: 'イスを' },
  { text: 'アレンダーで' },
  { text: '木っ端みじんに' },
  { text: 'どうして' },
  { text: '儲かるかって' },
  { text: '墓場なんです' },
  { text: '結局のところ' },
  { text: '売り切れとると' },
  { text: 'ｎ' },
  { text: '折り畳んで' },
  { text: '世紀末に' },
  { text: '謎かけでもしながら' },
  { text: '景品を持ち歩いてね' },
  { text: '箱やったらどうすんねん' },
  { text: '喧嘩になって' },
  { text: '対バンして' },
  { text: 'だーれも' },
  { text: '電気付けっぱなしやねん' },
  { text: 'うー言うて' },
  { text: 'お腹もペコペコですわ' },
  { text: 'ほんならね' },
  { text: '一月一日の事なんですけど' },
  { text: 'いや' },
  { text: 'すいません' },
  { text: '二月七日の話なんですけど' },
  { text: 'ポイントカードがね' },
  { text: 'どこ行ったんやいう話で' },
  { text: 'かゆ' },
  { text: 'アルコールをね' },
  { text: 'サッカーなんよなぁ' },
  { text: 'ブラインドタッチってできます？' },
  { text: 'パエリアなのか' },
  { text: '針時計がね' },
  { text: 'パニーニなんですよ' },
  { text: '三脚四脚五ギャグ言うて' },
  { text: '丑三つ時の由来なんですけど' },
  { text: 'ブレーカー落ちとんねん' },
  { text: 'オンでもね' },
  { text: '色んなことあってね' },
  { text: '相合傘したりとか' },
  { text: 'ダウン着たりとか' },
  { text: 'Wi-Fiのパスワードは' },
  { text: '燦然と輝いて' },
  { text: 'じゃあそう書いとけよ' },
  { text: '張り紙しとけや' },
  { text: '郵便局員が' },
  { text: 'これ火星の' },
  { text: 'ごみ箱のサイズにもよるやろ' },
  { text: 'どうして' },
  { text: '何でそんな事なんねんと' },
  { text: '免許も持ってへんし' },
  { text: 'ハナハナなんですよ' },
  { text: '一生懸命練習したソーラン節も' },
  { text: '雨降ってきて' },
  { text: '反響するし' },
  { text: '人間ゼミでやったんか？' },
  { text: 'ちょっとお前' },
  { text: 'お前に言うてんねん' },
  { text: '今観てる' },
  { text: 'お前' },
  { text: 'お前や' },
  { text: 'スマホで観てる' },
  { text: 'お前' },
  { text: 'お前に言うてんねん' },
  { text: 'コラー' },
  { text: 'こっち来いやー' },
  { text: 'エビやったんですよ' },
];

const gekiyaba = {
  makeSeed: () => randomSeed(scenes.length),
  shuffled: (seed: string, salt: number) => {
    return shuffle(scenes, seed, salt);
  }
}

export default gekiyaba
